// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB-iu0tzz2pxju14dg23Id6gVDLE1xG6s',
    appId: '1:447948535735:web:87127069a37e5cf7359a32',
    messagingSenderId: '447948535735',
    projectId: 'sirasafe-73b7d',
    authDomain: 'sirasafe-73b7d.firebaseapp.com',
    storageBucket: 'sirasafe-73b7d.appspot.com',
    measurementId: 'G-15VCCC5MLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-jl_UvVK3UIdQmrh-5Pnx9Ws30nVpjl4',
    appId: '1:447948535735:android:4a37b048a06015af359a32',
    messagingSenderId: '447948535735',
    projectId: 'sirasafe-73b7d',
    storageBucket: 'sirasafe-73b7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN6SxONu_PW5_E1WwNOI1sbR7THUstB4Y',
    appId: '1:447948535735:ios:d55befd103141c9d359a32',
    messagingSenderId: '447948535735',
    projectId: 'sirasafe-73b7d',
    storageBucket: 'sirasafe-73b7d.appspot.com',
    iosClientId: '447948535735-o275v11d8hobifn2jobspbjur2l1m5gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sirasafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN6SxONu_PW5_E1WwNOI1sbR7THUstB4Y',
    appId: '1:447948535735:ios:d55befd103141c9d359a32',
    messagingSenderId: '447948535735',
    projectId: 'sirasafe-73b7d',
    storageBucket: 'sirasafe-73b7d.appspot.com',
    iosClientId: '447948535735-o275v11d8hobifn2jobspbjur2l1m5gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sirasafe',
  );
}
